### ISSUE TITLE
AlienwareDllName not working

### ISSUE THREAD

**Issue by fma965** [Archomeda/lightfx-extender#7]
"LightFX": {
            "AlienwareDllName": "LightFX_orig.dll",

2015-03-11 17:38:44 - [DEBUG] DeviceManager - Alienware LightFX.dll not found

**Comment by fma965** [comment]
By hardcoding the following line it works so i guess it's a issue with the system path or filename?

```
if (InitializeLightFX(L"C:\\Windows\\System32\\LightFX_orig.dll", config->AlienwareBackupDllName)) {
```

**Comment by Archomeda** [comment]
Currently on mobile, so I can't test it. But I looked at my code and my guess is that at https://github.com/Archomeda/lightfx-extender/blob/master/src/Devices/LightFX2.cpp#L59 there seems to be missing a seperator between `GetSystemFolder()` and `name`. Try putting a backslash in between and see if that fixes it.

**Comment by fma965** [comment]
Hehe i literally just added a \ to the config file and it worked, then got a email telling me about your reply lol.

using
`hInstanceLightFX = LoadLibraryW((GetSystemFolder() + L"\\" + name).c_str());`
instead of
`hInstanceLightFX = LoadLibraryW((GetSystemFolder() + name).c_str());`

works atleast it does for 64bit not tested on 32bit

**Comment by fma965** [comment]
however from what i'm reading 

OS:64 bit   - Application:64 bit    FOLDERID_System = %windir%\system32
OS:64 bit   - Application:32 bit    FOLDERID_System = %windir%\system32

It doesn't do SysWOW64

https://msdn.microsoft.com/en-us/library/dd378457(v=vs.85).aspx

**Comment by Archomeda** [comment]
By adding that slash to the config, it seems to support my thoughts. Can you make a pull request where that slash is added on the line that I linked? Then I will take a look at it when I get home.

About the system32 folder,that's because of the file system redirector: https://msdn.microsoft.com/en-us/library/windows/desktop/aa384187%28v=vs.85%29.aspx

**Comment by fma965** [comment]
Yup all working just changed the code, Need to git clone etc then will make a pr.

Oh right, well both 32bit and 64bit so it's all good :)
